name: Current Ratings Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'
    
jobs:
  update:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        r-version: [4.2.0]

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
      - name: Run current ratings update
        run: Rscript "update_scripts/update_current_ratings.R"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git pull
          git add .
          git commit -m "[GHA] updated current ratings" || "no changes to commit"
          git push || echo "No changes to commit"
